// <auto-generated />
using System;
using MVC_PROJECT.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_PROJECT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426002211_AddIsClosed")]
    partial class AddIsClosed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_PROJECT.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceSessionId")
                        .HasColumnType("int");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceSessionId");

                    b.HasIndex("EnrollmentId", "AttendanceSessionId")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.AttendanceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendanceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CourseSectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("SessionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseSectionId");

                    b.ToTable("AttendanceSessions");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.CourseDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("CourseId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("CourseDepartments");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.CoursePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllowedAbsences")
                        .HasColumnType("int");

                    b.Property<int>("BestQuizzesCount")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("LectureAttendanceMarks")
                        .HasColumnType("int");

                    b.Property<int>("QuizMarks")
                        .HasColumnType("int");

                    b.Property<int>("SectionAttendanceMarks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("CoursePolicies");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.CourseSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentSectionId")
                        .HasColumnType("int");

                    b.Property<int>("TAId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentSectionId");

                    b.HasIndex("TAId");

                    b.HasIndex("CourseId", "DepartmentSectionId")
                        .IsUnique();

                    b.ToTable("CourseSections");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.DepartmentSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Number")
                        .IsUnique();

                    b.ToTable("DepartmentSections");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSectionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseSectionId");

                    b.HasIndex("StudentId", "CourseSectionId")
                        .IsUnique();

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxMark")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CourseSectionId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.QuizGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Mark")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PercentageScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("QuizId", "EnrollmentId")
                        .IsUnique();

                    b.ToTable("QuizGrades");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentSectionId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("UniversityId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentSectionId");

                    b.HasIndex("UniversityId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.AttendanceRecord", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.AttendanceSession", "AttendanceSession")
                        .WithMany("Records")
                        .HasForeignKey("AttendanceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_PROJECT.Models.Enrollment", "Enrollment")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceSession");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.AttendanceSession", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.CourseSection", "CourseSection")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("CourseSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSection");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Course", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.CourseDepartment", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.Course", "Course")
                        .WithMany("CourseDepartments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_PROJECT.Models.Department", "Department")
                        .WithMany("CourseDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.CoursePolicy", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.Course", "Course")
                        .WithOne("CoursePolicy")
                        .HasForeignKey("MVC_PROJECT.Models.CoursePolicy", "CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.CourseSection", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.Course", "Course")
                        .WithMany("CourseSections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_PROJECT.Models.DepartmentSection", "DepartmentSection")
                        .WithMany("CourseSections")
                        .HasForeignKey("DepartmentSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_PROJECT.Models.User", "TA")
                        .WithMany("CourseSections")
                        .HasForeignKey("TAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("DepartmentSection");

                    b.Navigation("TA");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.DepartmentSection", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.Department", "Department")
                        .WithMany("Sections")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Enrollment", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.CourseSection", "CourseSection")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_PROJECT.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSection");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Notification", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Quiz", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.CourseSection", "CourseSection")
                        .WithMany("Quizzes")
                        .HasForeignKey("CourseSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseSection");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.QuizGrade", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.Enrollment", "Enrollment")
                        .WithMany("QuizGrades")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_PROJECT.Models.Quiz", "Quiz")
                        .WithMany("QuizGrades")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Student", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_PROJECT.Models.DepartmentSection", "DepartmentSection")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MVC_PROJECT.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("MVC_PROJECT.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DepartmentSection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.AttendanceSession", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Course", b =>
                {
                    b.Navigation("CourseDepartments");

                    b.Navigation("CoursePolicy")
                        .IsRequired();

                    b.Navigation("CourseSections");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.CourseSection", b =>
                {
                    b.Navigation("AttendanceSessions");

                    b.Navigation("Enrollments");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Department", b =>
                {
                    b.Navigation("CourseDepartments");

                    b.Navigation("Sections");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.DepartmentSection", b =>
                {
                    b.Navigation("CourseSections");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Enrollment", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("QuizGrades");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Quiz", b =>
                {
                    b.Navigation("QuizGrades");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.User", b =>
                {
                    b.Navigation("CourseSections");

                    b.Navigation("Notifications");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
